# Generated by Django 5.1 on 2024-10-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_orden_ordenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
