# Generated by Django 5.1 on 2024-10-12 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_alter_carrito_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoproducto',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_productos', to='producto.carrito'),
        ),
    ]
