# Generated by Django 4.2.13 on 2024-06-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_alter_comment_author'),
        ('miapp', '0003_remove_post_image'),
    ]

    operations = [
    ]
