# Generated by Django 4.2.13 on 2024-06-09 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_merge_20240609_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
