# Generated by Django 5.1 on 2024-10-13 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_post_image'),
        ('producto', '0008_alter_carritoproducto_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='carrito',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario', to='producto.carrito'),
        ),
    ]
